# --- Подключение тем ---
include chicago95-theme.conf
#include dark-theme.auto.conf

# --- Настройка панелей и вкладок ---
# Расположение панели вкладок: top (сверху) или bottom (снизу)
tab_bar_edge top

# Стиль панели: fade (плавное затухание), slant (скошенные углы),.
# separator (разделители), powerline (стрелочки), custom
tab_bar_style separator

# Формат отображения текста на вкладке (индекс и название)
tab_title_template "{index}: {title}"

# Включает отслеживание мыши и кликабельность
clear_all_mouse_actions no

# Настройка зоны захвата границ окон (в пикселях)
window_drag_tolerance 5

# Отключает мерцание курсора, чтобы он не раздражал в меню mc
cursor_blink_interval 0

# Автоматически удалять пробелы в конце строк при копировании в буфер
strip_trailing_spaces smart

# --- Настройка шрифта --- (важно для ровных рамок и таблиц)
font_family      Fira Code
font_size        11.0
disable_ligatures never

# --- Прозрачность фона ---
background_opacity 0.95

# Размытие заднего фона (работает в KDE, GNOME, Hyprland и Wayland)
background_blur 20

# Разрешаем динамическое изменение прозрачности хоткеями
dynamic_background_opacity yes

# Нужно для взаимодействия с серверами, при подключении по ssh
# По умолчанию kitty автоматически выставляет TERM=xterm-kitty 
#term xterm-256color
# лучше вместо этого, на подключаемом cервере установить kitty-terminfo
# это добавит описание xterm-kitty в /usr/share/terminfo/ сервера

# ------------------------------------------------------------------------
# Цвет MC (есть в теме chicago95 )
# Классический насыщенный синий (основной фон mc)
#color4  #0000aa

# Классический яркий голубой (рамки и текст)
#color12 #5555ff

# (Опционально) Яркий белый текст на панелях mc
#color7  #aaaaaa
#color15 #ffffff

# ------------------------------------------------------------------------
# --- Горячие клавиши ---
# Открывать новое окно (сплит) в текущей папке
map ctrl+shift+enter launch --cwd=current

# Открывать новую вкладку в текущей папке
map ctrl+shift+t launch --type=tab --cwd=current

# Изменение прозрачности левая, правая стрелки
map ctrl+shift+left set_background_opacity -0.05
map ctrl+shift+right set_background_opacity +0.05


# Цвет MC (есть в теме chicago95 )
# Классический насыщенный синий (основной фон mc)
#color4  #0000aa

# Классический яркий голубой (рамки и текст)
#color12 #5555ff

# (Опционально) Яркий белый текст на панелях mc
#color7  #aaaaaa
#color15 #ffffff

# ------------------------------------------------------------------------
